backend:
  name: backend
  port: 8000
  image:
    repository: shampiniony/mts-backend
    tag: latest
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
