definitions:
  domain.PersonNode:
    properties:
      children:
        items:
          type: string
        type: array
      groupid:
        type: string
      groupname:
        type: string
      id:
        type: string
      image:
        type: string
      jobtitle:
        type: string
      name:
        type: string
      parents:
        items:
          type: string
        type: array
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /persons:
    get:
      description: Get a list of all persons
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.PersonNode'
            type: array
      summary: Retrieve all persons
      tags:
      - persons
  /persons/filter:
    get:
      description: Filters persons based on query parameters like id, name, and status.
      parameters:
      - description: Filter by ID
        in: query
        name: id
        type: string
      - description: Filter by Name
        in: query
        name: name
        type: string
      - description: Filter by Status
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.PersonNode'
            type: array
      summary: Filter persons based on query parameters
      tags:
      - persons
  /persons/search:
    get:
      description: Search for persons using a text query
      parameters:
      - description: Text to search for
        in: query
        name: text
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.PersonNode'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Search for persons
      tags:
      - persons
swagger: "2.0"
